## check development version of mboost
## see http://docs.travis-ci.com/user/languages/r/

# ## test multiple directories 
# ## (see https://lord.io/blog/2014/travis-multiple-subdirs/)
# env:
#  - TEST_DIR=pkg/mboostPatch
#  - TEST_DIR=pkg/mboostDevel

language: r
r:
 - release
 - devel

cache: packages 

# for codecov
r_packages:
  - covr

before_install:
  - tlmgr install amsmath amsfonts hyperref natbib graphics threeparttable xcolor doublestroke subfigure url tools booktabs oberdiek geometry

bioc_packages:
  - KEGGgraph
  - biomaRt

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
    Rscript -e 'library(covr); coveralls(line_exclusions = list("R/mboost_intern.R", "R/AAA.R" = 14:28))'
