# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  - ps: Bootstrap

# Adapt as necessary starting from here
environment:
  global:
    GCC_PATH: mingw_64
    R_ARCH: x64
    USE_RTOOLS: true
    R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  matrix:
    - configuration: release
      R_VERSION: release
      BIOC_USE_DEVEL: "FALSE"
    - configuration: devel
      R_VERSION: devel
      BIOC_USE_DEVEL: "TRUE"

before_build:
  - bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"

build_script:
  - travis-tool.sh install_bioc KEGGgraph biomaRt
  - travis-tool.sh install_deps
  - travis-tool.sh install_github hofnerb/stabs
  - travis-tool.sh install_github boost-R/gamboostLSS

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs
  ## push complete mboost.Rcheck folder as artifact
  - appveyor PushArtifact mboost.Rcheck   

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '*_*.tar.gz'
    name: Bits

  - path: '*_*.zip'
    name: Bits
